### ISSUE TITLE
lazy load tasks

### ISSUE THREAD

**Issue by blaadje** [blaadje/Todolist#35]

**Comment by tatiana-passarella** [comment]
I'm interested to contribute to solve this issue, can you describe better the issue please?

**Comment by blaadje** [comment]
Hey @tatiana-passarella, thanks a lot for your interest I'd be happy to help you contribute.

So atm the App component ([here](https://github.com/blaadje/Todolist/blob/master/src/components/App.vue#L286)) will call [getTasks](https://github.com/blaadje/Todolist/blob/master/src/core/db/methods.js#L9) method in order to retrieve **all** tasks.
Idea behind this issue was to potentially get the [selectedDate](https://github.com/blaadje/Todolist/blob/master/src/components/App.vue#L174) and retrieve only tasks for current/previous/next date at the app loading and while updating date. It would improve the perf with big database storage.

Let me know if this isn't clear or if you got other questions

**Comment by blaadje** [comment]
@tatiana-passarella  Do you still plan to contribute ? If so did you have time to check ? 😇
